# Generated by Django 4.2.3 on 2023-07-19 13:40

from django.db import migrations, models
import ecommerce_products.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce_products.utils.upload_image_path)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
