# Generated by Django 4.2.3 on 2023-07-19 18:13

from django.db import migrations, models
import ecommerce_products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_products.utils.upload_image_path),
        ),
    ]
