# Generated by Django 4.2.3 on 2023-07-20 14:03

from django.db import migrations, models
import ecommerce_products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصول'},
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce_products.utils.upload_image_path, verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
