# Generated by Django 4.2.3 on 2023-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_category', '0002_alter_productcategory_options'),
        ('ecommerce_products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='prodcuts', to='ecommerce_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
