# Generated by Django 4.2.3 on 2023-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_tag', '0002_remove_tag_products'),
        ('ecommerce_products', '0008_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='ecommerce_tag.tag'),
        ),
    ]
