# Generated by Django 4.2.3 on 2023-07-25 09:04

from django.db import migrations, models
import django.db.models.deletion
import ecommerce_products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0009_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecommerce_products.utils.upload_image_path, verbose_name='عکس گالری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_products.product')),
            ],
        ),
    ]
