# Generated by Django 4.2.3 on 2023-07-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0013_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'تصویر محصول'},
        ),
    ]
