# Generated by Django 4.2.3 on 2023-07-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
