# Generated by Django 4.2.3 on 2023-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شما')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='متن')),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'فرم تماس با ما',
                'verbose_name_plural': 'فرم های تماس با ما',
            },
        ),
    ]
