# Generated by Django 4.2.3 on 2023-07-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
