# Generated by Django 4.2.3 on 2023-07-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailclass',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='orderid', to='ecommerce_cart.orderclass'),
        ),
    ]
