# Generated by Django 4.2.3 on 2023-07-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
